GoogleCloudPlatform/cloud-sql-jdbc-socket-factory

pom.xml

Reference guide: http://central.sonatype.org/pages/apache-maven.html

Configure project for release per the Sonatype guide

---

pom.xml

- Set default tag to HEAD
- Use SSH for performing releases
- Create release tags with just the version number

Configure a few more knobs for releasing.

---

core/src/main/java/com/google/cloud/sql/CredentialFactory.java
core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java

Expose system property for custom credential factory.

---

core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java

Improve permission error message to mention curated role.

---

connector-j-5/pom.xml
connector-j-6/pom.xml
core/pom.xml
pom.xml
postgres/pom.xml

release 1.0.5

---

README.md
connector-j-5/pom.xml
connector-j-6/pom.xml
core/pom.xml
pom.xml
postgres/pom.xml

1. update all pom’s
2. Update README to 1.0.5

Prepare for 1.0.6-SNAPSHOT

---

pom.xml

Remove unnecessary dependency from root pom.

---

README.md

Add info about connecting IntelliJ

---

README.md
connector-j-5/pom.xml
connector-j-6/pom.xml
connector-j-8/pom.xml
core/pom.xml
examples/compute-engine/pom.xml
examples/getting-started/pom.xml
examples/mysql/compute-engine/pom.xml
examples/postgres/appengine-standard-java8/pom.xml
examples/postgres/compute-engine/pom.xml
pom.xml
postgres/pom.xml

* Fixed compatibility with JDK 9+
* Updated Postgres SocketFactory constructor to match new API signature 
* Added support for specifying IP types

Release v1.0.11

---

connector-j-5/src/main/java/com/google/cloud/sql/mysql/GrpcSocketFactory.java
connector-j-6/src/main/java/com/google/cloud/sql/mysql/GrpcSocketFactory.java
connector-j-8/src/main/java/com/google/cloud/sql/mysql/GrpcSocketFactory.java
core/pom.xml
core/src/main/java/com/google/cloud/sql/core/BaseGrpcSocketFactory.java
core/src/main/java/com/google/cloud/sql/core/CustomCertificateVerifier.java
core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java
core/src/main/proto/mygrpc.proto
postgres/src/main/java/com/google/cloud/sql/postgres/GrpcSocketFactory.java

add new socket factories that connect to proxy server via gRPC on port 3308.

add gRPC Socket Factory

---

connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java

Addressed #110.
I've confirmed this works on Java 8 GAE env - @ludoch can you verify it works for the new runtime?

Updated GAE check for Java11 compatibility.

---

connector-j-5/pom.xml
connector-j-6/pom.xml
connector-j-8/pom.xml
pom.xml
postgres/pom.xml

Fixes #112 and addresses part of #115.

Updated jnr-unixsocket and moved to asm 7.0. 

---

core/pom.xml

Update guava version.

---

README.md
connector-j-5/pom.xml
connector-j-6/pom.xml
connector-j-8/pom.xml
core/pom.xml
pom.xml
postgres/pom.xml

* Updated dependencies to new versions. 
* Minor cosmetic restructuring for code health.

Release v1.0.13

---

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
pom.xml

Deprecate USER_TOKEN_PROPERTY_NAME and add method alternatives.

---

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java

* Inlined and updated strings used for testing
* Added specific cases for stubs and generic cases that throw errors

Misc testing improvements

---

README.md

instructions for building the fat JAR

Updated readme.md with build instructions

---

.github/blunderbuss.yml

@GoogleCloudPlatform/cloud-sql-dpes FYI

Configure blunderbuss to auto-assign new issues.

---

r2dbc-mysql/pom.xml
r2dbc-mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java
r2dbc-postgres/pom.xml
r2dbc-postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java

Fixes #254 
Screenshots from Stackdriver to verify:

chore: update artifact names and user agents

---

.github/workflows/release-please.yaml
README.md
connector-j-5/pom.xml
connector-j-6/pom.xml
connector-j-8/pom.xml
core/pom.xml
pom.xml
postgres/pom.xml
r2dbc-core/pom.xml
r2dbc-mysql/pom.xml
r2dbc-postgres/pom.xml
versions.txt

This should update all of the versions in the pom files to whatever is set in `versions.txt`. We can also use different module names in `versions.txt` if eventually we decide that jdbc/r2dbc will have separate versions.

chore: configure release-please to auto-update versions

---

.build/build.sh
.build/build_uberjars.yaml

Adds cloud build configuration file and bash script to build and upload `jar-with-dependencies` and `jar-with-driver-and-dependencies` . 
Dependent on #274 .

chore: add cloud build configuration and build script

---

connector-j-5/pom.xml
connector-j-6/pom.xml
connector-j-8/pom.xml
core/pom.xml
pom.xml
postgres/pom.xml
r2dbc-core/pom.xml
r2dbc-mysql/pom.xml
r2dbc-postgres/pom.xml

chore: release 1.1.1-SNAPSHOT

---

renovate.json

See https://github.com/renovatebot/renovate/issues/7352

chore(renovate): Disable master issue creation until fixed

---

.github/workflows/tests.yml
.kokoro/tests/run_tests.sh

Adds a GitHub action to detect checkstyle violations

chore: create GitHub action for lint check

---

r2dbc-mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIntegrationTests.java
r2dbc-postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIntegrationTests.java

Improves code quality
- Fixes #334

chore: remove duplicated code and make tests more uniform

---

.github/renovate.json
sqlserver/pom.xml

Configure renovate to only allow jre8 versions.

chore(renovate): restrict updates to jre8 versions

---

.github/renovate.json

chore(renovate): fix allowlist for mssql-jdbc updates

---

.build/build.sh
.build/build_uberjars.yaml
pom.xml

Update the build script to include SQL Server artifacts and add configuration to javadoc plugin

chore: fixes to release process

---

README.md

Please provide a detailed description on what changes your PR will have.
- Fixes #<issue_number_goes_here>

docs: fix error in r2dbc URLs

---

README.md

Replaced all references to master branch with main

chore: rename master to main

---

docs/jdbc-mysql.md
docs/jdbc-postgres.md
docs/jdbc-sqlserver.md
docs/r2dbc-mysql.md
docs/r2dbc-postgres.md
docs/r2dbc-sqlserver.md

chore(docs): fix broken links in docs

---

.build/build.sh
.build/build_uberjars.yaml

Updating build script after folder reorganization

chore: updates to build script

---

docs/jdbc-mysql.md

I fixed the broken links in the docs `mysql-jdbc.md`
- Fixes #<issue_number_goes_here>

chore: fix broken links

---

.kokoro/java11/windows/common.cfg
.kokoro/java11/windows/continuous.cfg
.kokoro/java11/windows/periodic.cfg
.kokoro/java11/windows/presubmit.cfg
.kokoro/tests/run_tests.bat

Please provide a detailed description on what changes your PR will have.
- Fixes #<issue_number_goes_here>

chore(ci): run tests on Windows

---

core/pom.xml
pom.xml

Adding the dependencies from #478 to dependencyManagement

chore: add transitive deps to dependency management

---

.github/ISSUE_TEMPLATE/question.md

Fixes a spelling typo in the issue template

chore: fix typo in question issue template

---

docs/jdbc-postgres.md
docs/r2dbc-postgres.md

Add documentation for IAM authentication with Postgres drivers

chore: document postgres IAM Authentication

---

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java

Replacing [deprecated class](https://github.com/googleapis/google-http-java-client/blob/0ddb54a0e9841309b33d8f274508ee2c8cd64412/google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonFactory.java#L36)

chore: replace deprecated JacksonFactory with GsonFactory

---

pom.xml

Get full stack traces in logs from failing tests

chore: disable trimStackTrace in pom.xml

---

jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIamAuthIntegrationTests.java
r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIamAuthIntegrationTests.java

Temporarily add region tags to IAM Auth integration tests until we can write a dedicated sample. 

chore: add region tags for IAM auth connection code

---

README.md

chore: add link for Cloud SQL and IntelliJ

---

core/pom.xml

fix: add undeclared dependency

---

.gitignore
.release/update_versions.sh

chore: use GNU and BSD friendly sed command

---

.github/renovate.json
pom.xml

See https://issues.apache.org/jira/browse/MDEP-753 for details.

chore: pin version of maven-dependency-plugin

---

r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIamAuthIntegrationTests.java

fix(r2dbc): parse 'enable_iam_authn' as String or Boolean as needed

---

.github/renovate.json

chore: unpin analyze

---

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java

fix: include value of INSTANCE_CONNECTION_NAME when invalid

---

.kokoro/release/common.cfg
.kokoro/release/common.sh
.kokoro/release/drop.cfg
.kokoro/release/drop.sh
.kokoro/release/promote.cfg
.kokoro/release/promote.sh
.kokoro/release/stage.cfg
.kokoro/release/stage.sh

Enables automated releases to Maven using Kokoro.
Corresponding CL: cl/448382391

chore(ci): add kokoro build configs for maven release

---

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java

fix: default to using TLSv1.3

---

.github/workflows/lint.yaml

Reverts GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1050

chore: revert previous PR which edited lint workflow

---

.github/flakybot.yaml
.github/workflows/tests.yml
core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
pom.xml

chore: configure Flakybot for tests running on GitHub Actions

---

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java

fix: throw exception on invalid IAM Authn config

---

.github/workflows/release.yml

This should be `TAG_NAME`
https://github.com/tubone24/update_release#environment-variables

chore: update env var name in release workflow

---

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
core/src/main/java/com/google/cloud/sql/core/InstanceData.java
core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java

chore(refactor): add fetchInstanceData method to SqlAdminApiService

---

.github/workflows/codeql.yml

Adding codeql security scan, scorecard is next.

ci: add codeql action for security scan

---

.github/workflows/scorecard.yml

Add ossf scorecard action to scan repo.

ci: add scorecard security scan

---

.github/renovate.json
.github/workflows/coverage.yml
.github/workflows/labels.yaml
.github/workflows/lint.yaml
.github/workflows/release.yml
.github/workflows/tests.yml

Remove `Pinned-Dependencies` alerts

ci: pin actions to shas

---

core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java

fix: log error when token is invalid

---

.github/workflows/tests.yml

Related to https://github.com/graalvm/setup-graalvm/issues/42

chore: fix broken graalvm build

---

core/pom.xml

deps: Upgrade com.google.guava/guava

---

core/pom.xml
jdbc/mariadb/pom.xml
jdbc/mysql-j-5/pom.xml
jdbc/mysql-j-8/pom.xml
jdbc/postgres/pom.xml
jdbc/sqlserver/pom.xml
r2dbc/core/pom.xml
r2dbc/mysql/pom.xml
r2dbc/postgres/pom.xml
r2dbc/sqlserver/pom.xml

deps: Update dependency com.google.auth:google-auth-library-oauth2-http to v1.19.0
deps: Update dependency com.google.auth:google-auth-library-credentials to v1.19.0
deps: Update dependency com.google.api:gax to v2.31.0
deps: Update dependency com.google.api-client:google-api-client to v2.2.0
deps: Update dependency com.google.http-client:google-http-client-gson to v1.43.3
deps: Update dependency com.google.http-client:google-http-client to v1.43.3
deps: Update guava from 31.1-android to 32.1.1-android

deps: Update dependencies related to client libraries 

---

pom.xml

deps: Update native-image.version to v0.9.23
deps: Update dependency org.graalvm.sdk:graal-sdk to v22.3.2

deps: Update graalvm libraries

---

core/src/main/java/com/google/cloud/sql/core/ServiceAccountImpersonatingCredentialFactory.java
core/src/test/java/com/google/cloud/sql/core/ServiceAccountImpersonatingCredentialFactoryTest.java

Creates a new kind of CredentialFactory that can impersonate credentials. 
Part of #1168

feat: Add service account impersonation credentials factory.

---

.github/auto-label.yaml
.github/release-please.yml
.github/release-trigger.yml
.github/trusted-contribution.yml
.kokoro/build.bat
.kokoro/build.sh
.kokoro/coerce_logs.sh
.kokoro/common.cfg
.kokoro/dependencies.sh
.kokoro/populate-secrets.sh
.kokoro/trampoline.sh

Apply nominal changes to standard project structure typically generated by owlbot. There are not many significant
changes since the files were generated automatically to begin with.

chore(ci): Update kokoro release to latest generated files.

---

.github/renovate.json

chore: migrate renovate config and group dependencies

---

.github/scripts/run_tests.sh
core/pom.xml
core/src/main/java/com/google/cloud/sql/CredentialFactory.java
core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
core/src/main/java/com/google/cloud/sql/core/package-info.java
core/src/main/java/com/google/cloud/sql/nativeimage/CloudSqlFeature.java
core/src/main/java/com/google/cloud/sql/package-info.java
core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
core/src/test/java/com/google/cloud/sql/core/TestKeys.java
jdbc/mariadb/pom.xml
jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java
license-checks.xml
pom.xml
r2dbc/core/pom.xml
r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java
r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
r2dbc/core/src/test/java/com/google/cloud/sql/core/TestKeys.java
r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java
r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java
r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java

chore: Add google-cloud-shared-config and update build configs so that they pass

---

.github/release-please.yml
docs/jdbc-mariadb.md
docs/jdbc-mysql.md
docs/jdbc-postgres.md
docs/jdbc-sqlserver.md
docs/r2dbc-mysql.md
docs/r2dbc-postgres.md
docs/r2dbc-sqlserver.md

chore: configure release-please to update released version in doc files

---

.github/renovate.json

chore: update renovate config to ignore some deps

---

docs/jdbc.md
docs/r2dbc.md

docs: update titles

---

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
core/src/main/java/com/google/cloud/sql/core/InstanceData.java
core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java
core/src/main/java/com/google/cloud/sql/core/Refresher.java
core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
core/src/test/java/com/google/cloud/sql/core/PauseCondition.java
core/src/test/java/com/google/cloud/sql/core/RefresherTest.java
core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java

Adds unit tests to ensure that the Refresher logic is working.

test: Add RefresherTest to unit test the Refresher 

---

core/src/main/java/com/google/cloud/sql/ConnectionConfig.java
core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
core/src/test/java/com/google/cloud/sql/ConnectionConfigTest.java
jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java

chore: Set postgres Unix path suffix as a property on ConnectionConfig

---

core/src/main/java/com/google/cloud/sql/core/ConnectorKey.java
core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
core/src/test/java/com/google/cloud/sql/core/ConnectorKeyTest.java

feat: Identify the connector for a ConnectionConfig by it's unique configuration

---

core/src/main/java/com/google/cloud/sql/core/Refresher.java

chore: Better name for the lock field in Refresher

---

.github/renovate.json
core/pom.xml
core/src/main/java/com/google/cloud/sql/core/Connector.java
core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java
core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
core/src/main/java/com/google/cloud/sql/core/Refresher.java
core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java
jdbc/mariadb/pom.xml
jdbc/postgres/pom.xml
jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
pom.xml

feat: use SLF4J for logging

---

core/src/main/java/com/google/cloud/sql/ConnectorRegistry.java
core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
docs/configuration.md

feat: Add reset() and shutdown(). Fixes #1687.

---

.github/renovate.json

chore: fix commit prefix

---

docs/jdbc.md
docs/r2dbc.md

chore: fix release-please annotations on READMEs

---

core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepositoryFactory.java
core/src/main/java/com/google/cloud/sql/core/Connector.java
core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryTest.java
core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java
core/src/test/java/com/google/cloud/sql/core/StubConnectionInfoRepository.java
core/src/test/java/com/google/cloud/sql/core/StubConnectionInfoRepositoryFactory.java
r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java
r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java

fix: Call force refresh when r2dbc connection is invalid

---

jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IAMServiceAccountImpersonationIntegrationTests.java

chore: correct misconfigured integration test

---

core/src/test/java/com/google/cloud/sql/core/RefresherTest.java

chore: update test to improve debug failures

---

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
core/src/main/java/com/google/cloud/sql/core/Refresher.java
core/src/main/java/com/google/cloud/sql/core/TerminalException.java
core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java
core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java
core/src/test/java/com/google/cloud/sql/core/RefresherTest.java

feat: Background refresh stops on unrecoverable Admin API response

---

core/pom.xml
jdbc/mariadb/pom.xml
jdbc/mysql-j-8/pom.xml
jdbc/postgres/pom.xml
jdbc/sqlserver/pom.xml
r2dbc/mysql/pom.xml
r2dbc/postgres/pom.xml
r2dbc/sqlserver/pom.xml

chore: use SLF4J for test logging

---

r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java
r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresPoolRemoteValidationIntegrationTests.java

fix: Update R2DBC connection validation to async

---

.github/workflows/tests.yml
jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresQuotaProjecImpersonationtIntegrationTests.java
jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresQuotaProjectIAMAuthIntegrationTests.java

Add new integration tests for Quota Project feature:
1. Quota Project + IAM Authentication
2. Quota Project + Service Account Impersonation

chore: Add integration tests for Quota Project feature.

---

docs/r2dbc.md
pom.xml
r2dbc/mariadb/pom.xml
r2dbc/mariadb/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMariadb.java
r2dbc/mariadb/src/main/resources/META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider
r2dbc/mariadb/src/test/java/com/google/cloud/sql/core/R2dbcMariadbIamAuthIntegrationTests.java
r2dbc/mariadb/src/test/java/com/google/cloud/sql/core/R2dbcMariadbIntegrationTests.java
versions.txt

Add support for MariaDB R2DBC driver as requested by customers.
Fixes #990

feat: Add r2dbc support for MariaDB

---

core/pom.xml

Reverts GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1924

chore: revert "chore: Update GAX dependency scope to provided."

---

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java
core/src/main/java/com/google/cloud/sql/core/RefreshAheadStrategy.java
core/src/main/java/com/google/cloud/sql/core/RefreshStrategy.java
core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java
core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java

Introduces the RefreshStrategy interface and updates RefreshAheadStrategy to implement that interface. 
Part of #992

chore: Introduce the RefreshStrategy interface (part of #992)

---

core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java

Java 8 thread and timing is not as reliable as newer JVMs. This introduces an extra small delay in the tests 
that test the expiration of the data so that it works reliably in Java 8.

test: Fix flaky test in lazy refresh, fixes #1980.

---

docs/jdbc.md

Update serverless products lazy cert refresh is useful for

docs: update serverless products lazy cert refresh is useful for

---

core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactory.java

chore: update typo in comment

---

.ci/cloudbuild.yaml

Adds cloudbuild build steps to run private IP instance tests on Cloud Build

ci: add cloudbuild.yaml for psa integration tests

---

.github/workflows/codeql.yml

Updates codeql-action from 3.27.5 to 3.28.15

ci: update deps for codeql.yml
