.travis.yml, pom.xml
Updated POM file to only run javadoc/source/gpg plugins during a release.
=> Fix #9 - Add Travis CI configuration.

pom.xml, src/test/java/com/google/cloud/sql/mysql/SslSocketFactoryTest.java
Use MockitoAnnotations.initMocks instead of MockitoRule.
=> Test compatibility with older Mockito versions.

pom.xml
This will pick up new version (1.22) of google-api-client which has improvements to reliability of retrieving credentials on GCE.
=> Bump up API version dependency

README.md, core/src/main/java/com/google/cloud/sql/mysql/SslSocketFactory.java, pom.xml, postgres/pom.xml, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
The core code in SslSocketFactory is reused as is.
The main difference between the MySQL implementation and the Postgres
implementation is that the user has to specify the instance name via the
`socketFactoryArg` property instead of a custom property as the Postgres
socket factory does not have access to the params.
There needs to be some cleanup in the code to move the common code out
of the 'mysql' package, but I'll leave it to a separate CL to keep this
small.
We also need to consider moving this code to a more 'generic' repo as
this one is mysql-specific, but that's a larger unertaking left to a
separate exercise.
=> Add Postgres support for the Socket Factory.

connector-j-5/pom.xml, connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/pom.xml, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, core/pom.xml, core/src/main/java/com/google/cloud/sql/core/CredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/SslSocketFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/TestKeys.java, pom.xml, postgres/pom.xml, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
- Move the 'core' classes from 'mysql' Java package to 'core' package.
- Change 'mysql-socket-factory' to 'jdbc-socket-factory' in non-mysql
specific artifact IDs.
=> Naming cleanup:

examples/mysql/compute-engine/README.md, examples/mysql/compute-engine/pom.xml, examples/mysql/compute-engine/src/main/java/com/google/cloud/sql/mysql/example/ListTables.java, examples/postgres/compute-engine/README.md, examples/postgres/compute-engine/pom.xml, examples/postgres/compute-engine/src/main/java/com/google/cloud/postgres/example/ListTables.java
MySQL specific example is "moved" to a mysql subdirectory.
Note: I left the original MySQL example in place as the docs still
reference it. I will remove it once the docs are updated to point to the
new location.
=> Add Postgres version of Compute Engine example.

connector-j-5/pom.xml, connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/pom.xml, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, examples/postgres/appengine-standard-java8/pom.xml
Adds an update for using unix sockets with the j5 and j6 connector factories, similar to https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/56/.
=> Unix Sockets for j5 and j6 connectors. 

core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/UsageMetricsHttpRequestInterceptor.java
Relies on the presence of a `USER_TOKEN_PROPERTY_NAME` property containing the user agent token.
An example of the client side usage is in https://github.com/spring-cloud/spring-cloud-gcp/commit/bc34b667a3595d2387a4057bf1a0d6f1b117e9d1
=> Adds usage tracking

core/pom.xml
Helps with #65.
Excludes Findbugs and Guava from being brought in by sqladmin, and also explicitely adds the dependence on these libraries, rather than relying on the transitive.
=> Fix findbugs and guava dependencies

core/pom.xml, examples/getting-started/pom.xml
This version uses google-api-client 1.23.0 instead of 1.22.0.
1.23.0 is already in use by other dependencies (e.g., everything at
google-cloud-java).
The fact that this dependency is pulling 1.22.0 is causing diamond
dependency issues in Spring Cloud GCP.
We had to manually set the version to be used on our side but,
ideally, this project should set the right version.
Better yet, this version should be obtained from dependencyManagement,
so we could use BOMs and not enforce any versions.
=> Upgrades SQLAdmin version

connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
Fixes #77. 
After speaking with the GAE Java team, it should be safe to check two different points:
* Environment variable "GAE_ENV" should be set to `"standard"`
* System property "com.google.appengine.runtime.environment" should be set to "Production"
If these two conditions are true and not running on GAE Standard production, it should be considered a bug. 
Additionally, this adds a check for the environment variable `"CLOUD_SQL_FORCE_UNIX_SOCKET"` that, if set, will force the library to attempt to connect through a unix socket.
=> Improve GAE Standard detection

README.md
The artifact names in maven central have a dash after the 'j' (https://repo.maven.apache.org/maven2/com/google/cloud/sql/)
=> Fix typos in artifact names

core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/SslSocketFactoryTest.java, pom.xml
`javax.xml.bind.DatatypeConverter` is not available out of the box on modularized JVMs, but since this project is already targeting 1.8, we can use `java.util.Base64` which was introduced then.
I also updated a few maven plugins so the build wouldn't die on current JDKs.
=> Use built in base64 to allow use on jdk9+

connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, core/src/main/java/com/google/cloud/sql/core/SslSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/SslSocketFactoryTest.java, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
Cloud SQL instances can have more IPs than just a primary IP, this change allows users to specify what IP type they would prefer to use when connecting.
=> Add support for specifying a list of preferred IP types

connector-j-8/pom.xml, connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
mysql-connector-java 8.0.13 introduced a major backwards incompatible change in the `SocketFactory` API. This makes sure the cloud SocketFactory implements both old and new APIs.
```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class com.google.cloud.sql.mysql.SocketFactory does not define or inherit an implementation of the resolved method abstract connect(Ljava/lang/String;ILcom/mysql/cj/conf/PropertySet;I)Ljava/io/Closeable; of interface com.mysql.cj.protocol.SocketFactory.
at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.ja …
```
=> Support new SocketFactory API in mysql-connector-java 8.0.13.

connector-j-5/pom.xml, connector-j-6/pom.xml, connector-j-8/pom.xml, core/pom.xml, core/src/test/java/com/google/cloud/sql/core/SslSocketFactoryTest.java, postgres/pom.xml
Fixes #121.
Notes:
* `1.28.0` of `google-api-services-sqladmin` brings `guava` and `findbugs` up to matching versions, so I removed the substitutions. 
* `joda-time` recommends moving to `java.time` for Java8, so I replaced it accordingly.
=> Update dependencies to more recent versions. 

connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
Consolidates the "connect" function logic from being implemented in each Factory into the core Socket Factory. 
Notable changes:
* Renamed core "SslSocketFactory" to "CoreSocketFactory" to better reflect it now returns multiple types of sockets
* Renamed the "create" function to "createSslSocketFactory"
* Implemented a new "create" function containing the ssl/unix socket determination and implemented in each factory 
* As a side effect, cleaned up the way "SocketFactoryArg" deprecation was handled that fixes #113
=> Consolidate "connect" logic from individual factories into core SocketFactory.

postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
Remove unnecessary instance initialization from postgres module.
=> Remove unnecessary instance initialization. 

core/pom.xml, core/src/main/java/com/google/cloud/sql/CredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
This should enable use of [Workload Identities](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) on GKE, which requires [this fix](https://github.com/googleapis/google-auth-library-java/pull/283) included in google-auth-library-oauth2-http 0.16.2
The solution isn't terribly beautiful but it seemed like a simple way to do it while maintaining backwards compatibility.
=> Using google-auth-library-oauth2-http to get default credentials

README.md, connector-j-5/pom.xml, connector-j-6/pom.xml, connector-j-8/pom.xml, core/pom.xml, pom.xml, postgres/pom.xml
* Improved initial start-up time:
* Generate the initial RSA key pair asynchronously. (#142)
* Remove static call on instance for Postgres. (#146)
* Now uses `google-auth-library-oauth2-http` to get default credentials (#151)
=> Release v1.0.15

renovate.json
These versions need to be pinned to the major version for each different major package.
=> Configure Renovate to ignore mysql-connector-java updates.

README.md, connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-6/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, connector-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
- Adds new `unixSocket` property, which which can be used to specify a path to a unix socket that will connect to an instance
- Deprecates `"CLOUD_SQL_FORCE_UNIX_SOCKET"` env var in favor of the above property
- Disables the use of the `/cloudsql` unix socket by default when on GAE or GCF
Fixes #172
=> Improve handling of connections through unix domain sockets. 

README.md, connector-j-5/pom.xml, connector-j-6/pom.xml, connector-j-8/pom.xml, core/pom.xml, pom.xml, postgres/pom.xml
- Several improvements to unix socket handling (#210):
- Added support for new `unixSocket` property, which can be used to specify a path to a unix socket instead of connecting over TCP
- Configuring with the `CLOUD_SQL_FORCE_UNIX_SOCKET` env var has been deprecated. Please set the `unixSocket` property to `/cloudsql/INSTANCE_CONNECTION_NAME` in your config instead. 
- Automatic enabling of use of the `/cloudsql/` Unix domain socket when running in Google App Engine and Google Cloud Function environments has been disabled. The recommended way to connect is to continue to use TCP connections, but the behavior can be replicated using the `unixSocket` property listed above. 
- Added support for project ids that are using the legacy "domain-scoped" format (#209)
=> Release v1.0.16.

pom.xml
Tests are failing in #221 because `plexus-compiler-javac-errorprone` is incompatible with `error_prone_core` v2.4.0.  The [Error Prone documentation](https://errorprone.info/docs/installation) has updated information on how to install Error Prone in Maven, and the updated method is used in this PR.
=> Updates pom.xml to use updated version of Error Prone

renovate.json
Only updates guava dependency when new `-android` version is released, because `-jre` is incompatible with the dependencies (see #241 )
=> chore: added rule for guava dependency in renovate.json

pom.xml, r2dbc-mysql/pom.xml, r2dbc-postgres/pom.xml
* Move scope of r2dbc driver dependencies to provided
* Add r2dbc driver dependencies to `jar-with-driver-and-dependencies` profile
* Update filename for jars build with `jar-with-driver-and-dependencies` profile
=> chore: moved r2dbc driver scope to provided and updated build profiles

.github/release-please.yml
Adding [this line to the config](https://github.com/googleapis/repo-automation-bots/tree/master/packages/release-please#configuration) should get the release-please bot to automatically generate releases for us.
=> chore: tell release-please to create release tags

.github/release-please.yml, .github/workflows/release-please.yaml
Updating our Release Please configuration to use the bot to generate PRs and the Github action to tag releases.
=> chore: use github action to tag releases

README.md
Added info on adding R2DBC connectors as dependencies and forming connection URLs. For now, I just included the info in existing sections, but we might want to think about reformatting this README.
- Fixes #289
=> docs: add R2DBC connector info to README

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
Update the SQLAdmin API to use an instance name with a region prefix with the format `<region>~<instance-name>` to prevent issues with conflicting instance names when sqladmin v1 is released and instance names become regionally unique instead of globally unique.
Note: these changes were tested locally using the integration tests from #301.
=> feat: use regionalized instance ids to prevent global conflicts with sqladmin v1

README.md, connector-j-6/pom.xml
Deprecate the mysql-socket-factory-connector-j-6 artifact and instead point users to the j-8 artifact. The j-6 version of the connector has been abandoned for some time, and the j-8 version is presumed to be backwards compatible. 
- Fixes #<issue_number_goes_here>
=> feat(mysql): Deprecated the mysql-socket-factory-connector-j-6 artifact

core/pom.xml, r2dbc/core/pom.xml
Declare used dependencies in `pom.xml` explicitly instead of relying on transitive dependencies.
Maybe it is better to `dependencyManagement` everything, but that feels like a separated PR.
- Fixes #477
=> fix: declare used maven dependencies explicitly

.kokoro/tests/run_tests.sh, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
Require TLS v1.3 when connecting with IAM auth so that OAuth2 token is encrypted during handshake.
- Fixes b/183540928 (internal)
=> fix: require TLSv1.3 when connecting using IAM authentication

r2dbc/core/pom.xml
Explicitly excluded the optional `io.micrometer:micrometer-core` dependency which was causing the linkage checker to fail in https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/2073
cc @suztomo
- Fixes #507
=> fix: exclude unreachable optional dependency in r2dbc-core

jdbc/sqlserver/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Excluding more artifacts that cause failures in https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/2073.
Note that even after these exclusions, the MaximumLinkageErrorsTest in the PR above fails due to new linkage errors.
- Fixes https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/507
=> fix: exclude the unreachable dependencies that have xerces-impl

.github/renovate.json
For now, exclude v1 from renovatebot updates
=> chore: exclude sqladmin v1 in dependency updates

r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
Updates the SSL Customizer used in r2dbc core to pull the most recent SSLData on each connection.
- Fixes #472
=> fix(r2dbc): fetch updated SSLData for each new connection

core/pom.xml, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
Use bouncycastle instead of internal sun.security APIs to generate certs for tests. I looked into using `java.security.cert` but most examples I saw either used bouncycastle or used `sun.security` or some other internal API
- Fixes #551
=> fix: remove dependency on internal sun.security.x509 classes

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, pom.xml
=> fix: only replace refresh result if successful or current result is invalid

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
Strips trailing `.` characters from access tokens
- Fixes #565
=> fix: strip padding from access tokens if present

.github/workflows/tests.yml, .kokoro/tests/run_tests.sh, core/pom.xml, jdbc/mysql-j-5/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, pom.xml, r2dbc/core/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Using maven-dependency-plugin, this commit cleans up our dependency
tree. The plugin is now run as part of the lint action and will catch
any undeclared used dependencies, or any declared unused dependencies.
All transitive dependencies are now declared where they are required.
The top level POM is just for build information now.
Fixes #656.
=> fix: Ensure all required dependencies are declared

core/pom.xml, jdbc/mysql-j-5/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, pom.xml, r2dbc/core/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Previously, attempts to run the assembly plugin would fail because the
parent was empty. Now that we've removed all dependencies from the
parent and placed them where they belong in the respective children
artifacts, the parent is empty. This commit updates the configuration of
the assembly step to skip the parent and only run for the children.
=> chore: skip assembly for parent

.kokoro/tests/run_tests.sh, .kokoro/tests/run_tests_java11.bat, .kokoro/tests/run_tests_java17.bat
Fix an issue where the PATH variable wasn't being properly set, leading to the wrong Java version sometimes being used for tests.
=> chore: fix path setting issue with Windows tests

.github/workflows/coverage.yml, .github/workflows/tests.yml
Sometimes these checks automatically fail when a PR is incompatible with Java 8.
=> chore: use latest LTS java version for lint and coverage checks

core/pom.xml, jdbc/mysql-j-5/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, pom.xml, r2dbc/core/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Trying graal-sdk 21.3.2 (old but patched), a change on top of Shubha's #827 .
-------------
- chore(deps): update dependency org.apache.maven.plugins:maven-javadoc-plugin to v3.4.0 (#821)
- chore(deps): update dependency org.sonatype.plugins:nexus-staging-maven-plugin to v1.6.13 (#820)
- chore(deps): update dependency org.mockito:mockito-core to v4.5.1 (#822)
- chore(deps): update dependency io.r2dbc:r2dbc-spi to v1 (#825)
- feat(jdbc/postgres): add compatibility for GraalVM native image (#805)
- chore(deps): update dependency org.apache.maven.plugins:maven-dependency-plugin to v3.3.0 (#774)
- chore(deps): update dependency org.ow2.asm:asm-util to v9.3 (#803)
- chore: fix path setting issue with Windows tests (#828)
- chore: use latest LTS java version for lint and coverage checks (#829) …
=> deps: try graal-sdk 21.3.2 (old but patched)

jdbc/mysql-j-5/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
All of the classes show up in the JAR after building once these were introduced. @hessjcg was able to track down the root cause to be this change:  
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/commit/64cfee110ec54272c45fe4b0d150182c65c8c828
The `test` scope was added to fix a failing lint check:
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/runs/6236244256?check_suite_focus=true
Fixes #881
=> fix: add back missing dependencies to JAR files

r2dbc/postgres/pom.xml
The r2dbc driver has a new artifact id, so we have to manually bump
=> chore: update r2dbc-postgresql to new artifact id

.github/renovate.json
This disables automatic rebases for Renovate. Most rebases are wasted and end up spamming emails and consuming test quota -- with this we can use the checkbox to force a rebase when a PR needs to be merged.
=> chore: disable automatic rebases

core/pom.xml, core/src/main/java/com/google/cloud/sql/CredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
=> fix: downscope credentials used for IAM AuthN login

.github/scripts/run_tests.sh, .github/workflows/tests.yml, .kokoro/release/common.cfg
Compiling with Java 11 will allow us to merge the tests that are blocked on Java 8 test failures.
=> chore: build with java 11 for java 8 tests

.github/workflows/release.yml
following the example here: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-2
=> chore: set multiline string to env var in workflow

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, pom.xml, r2dbc/core/pom.xml, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/TestKeys.java, r2dbc/core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, r2dbc/mysql/pom.xml, r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java, r2dbc/mysql/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysqlTest.java, r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java, r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java
Currently there is no way to use the R2DBC connectors and specify IP Type, which is a glaring feature gap. This PR adds support for setting IP type when configuring an R2DBC connection factory and adds tests to make sure the right IP address is being used.
Lots of testing boilerplate here, but the relevant files to look at are:
- `CoreSocketFactory.java`
- `GcpConnectionFactoryProvider.java`
- `CloudSqlConnectionFactory.java`
- `GcpConnectionFactoryProviderMysqlTest.java` (for the test)
Also added `GcpConnectionFactoryProviderTest.java` which is mostly just providing a stub for the CoreSocketFactory which can be used in tests that extend the class
=> feat:  enable setting ipType connection option for r2dbc drivers

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
This change lowers the log level for subsequent connections to fine.  The reason is that the log doesn't offer any actionability for most users.  This log gets printed pretty frequently, scrolling up the other logs from the application.  Existing users who still want to know connections being made can increase their logger verbosity.
=> chore: remove periodic logging of connection creation

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
None of the other connectors use it and it never launched anyway.
=> chore: remove use of regionalized API

.github/workflows/coverage.yml, .github/workflows/labels.yaml, .github/workflows/lint.yaml, .github/workflows/release.yml, .github/workflows/tests.yml
Remove `Token-Permissions` alerts
=> ci: make top-level workflow permissions read-only

core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java, core/src/test/resources/logging.properties, pom.xml
By commenting out the java.util.logging.config.file configuration, the test logging can be restored. This change ensures the build log is clean.
=> chore: disable test logging with pom.xml

docs/r2dbc-mysql.md, r2dbc/mysql/pom.xml, r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java
The R2DBC driver, r2dbc-mysql, has transitioned to new maintainership as detailed in [this GitHub issue](https://github.com/mirromutth/r2dbc-mysql/issues/251). The new fork has been updated to accommodate recent r2dbc-spi changes, making it compatible with the General Availability (GA) version 1.0.0.
Given that this fork was officially endorsed by the original owner, it is a reliable alternative to switch to io.asyncer:r2dbc-mysql. We kindly request that this change be expedited and released, as it is currently impeding our migration from Spring Boot 2 to Spring Boot 3.
=> feat: prefer io.asyncer:r2dbc-mysql

.kokoro/release/stage.cfg
We need to store release artifacts in Kokoro to generate SBOMs for released software.
When reviewing, please check that:
- The build passes
- All software artifacts generated by `mvn install` are accounted for
=> ci: Update kokoro stage job to store release artifacts

r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java, r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIntegrationTests.java, r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIamAuthIntegrationTests.java, r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIntegrationTests.java, r2dbc/sqlserver/src/test/java/com/google/cloud/sql/core/R2dbcSqlserverIntegrationTests.java
Remove extraneous test code that created tables and inserted data. If the client 
can perform `select 1` or `select now`, the connection succeeded.
Fixes #1273 
Fixes #1262 
Fixes #1272
=> test: Simplify r2dbc integration tests.

jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIamAuthIntegrationTests.java, jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIntegrationTests.java, jdbc/mysql-j-5/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ5IntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IamAuthIntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IntegrationTests.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIamAuthIntegrationTests.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIntegrationTests.java, jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerIntegrationTests.java
Remove extraneous test code that created tables and inserted data. If the client 
can perform `select 1` or `select now`, the connection succeeded.
=> test: Simplify jdbc integration tests.

pom.xml
This was merged by mistake.
This reverts commit 6b9d7dc5628cd5992c08a3ea232ae57c322a538d.
=> fix: Revert Update dependency com.google.errorprone:error_prone_core to v2.19.1

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java, core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java, core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java
Simplifies the logic when attempting to get the first token for a connection with IAM AuthN enabled. Also, adds logic
to retry the token request 3 times if it initially fails. 
Fixes #1288 
Fixes #1127
=> fix: Retry when attempting to get the auth token

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/RefreshCalculator.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/RefreshCalculatorTest.java
This will make the certificate refresh timing in the java jdbc connector consistent with the other connectors.
=> feat: Use new certificate refresh logic 

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
There was a subtle bug in the way we were using futures during the process to refresh the tokens and ephemeral
certificates. Occasionally an API request would fail, causing the refresh process to hang. 
Now the code uses `Futures.whenAllComplete()` instead of  `Futures.whenAllSucceded()` so that an api request error
will be propagated rather than ignored.
=> fix: Fix futures to avoid a hanging future when an api request fails on refresh

core/src/main/java/com/google/cloud/sql/core/ApiFetcherFactory.java, core/src/main/java/com/google/cloud/sql/core/ApplicationDefaultCredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/CredentialFactoryProvider.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcherFactory.java, core/src/main/java/com/google/cloud/sql/core/package-info.java, core/src/main/java/com/google/cloud/sql/package-info.java, core/src/test/java/com/google/cloud/sql/core/CredentialFactoryProviderTest.java, core/src/test/java/com/google/cloud/sql/core/StubApiFetcherFactory.java
Removes public access from unused methods.  Moves non-public classes into the core package.  This should have no impact existing implementations using the connector.
=> chore: Clean up existing public java api 

jdbc/mysql-j-5/pom.xml
This rolls back PR #1290, which tried to use ${project.version} instead. Unfortunately the expansion doesn't work when you use gradle to pull the dependencies. 
Fixes #1333 
See also [GoogleCloudPlatform/spring-cloud-gcp #1982](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1982)
=> fix: Use explicit project version in distributionManagement section

core/src/main/java/com/google/cloud/sql/core/AccessTokenSupplier.java, core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java
Between version v1.13 and v1.14 of google-auth-library-oauth2, a bug was fixed that changed the behavior of how downscope tokens are refreshed. Prior to the fix, the code could downscope an oauth2 token, then the refresh the downscoped token. After the fix, the code must first refresh the original oauth2 token, then downscope it again.
In order to incorporate this new behavior into our code, we needed to encapsulate the operation of refreshing and 
downscoping a token. This change became too big for one PR, so I split the implementation into 3 PRs.
This PR introduces a new class and interface `AccessTokenSupplier` and `DefaultAccessTokenSupplier` along with extensive unit tests. This new class encapsulates the logic to refresh a token, duplicating the logic in `CloudSqlInstance`
PR #1330 …
=> chore: add AccessTokenSupplier

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java, core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java, core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java
Refactors `CloudSqlInstance` and `SqlAdminApiFetcher` and tests to use the new `DefaultAccessTokenSupplier`, removing the duplicate refresh token code. Add unit tests to
cover CloudSqlInstance behavior.
This PR follows #1329
Related to issue #1294
=> chore: Use AccessTokenSupplier, remove duplicate code from CloudSqlInstance.

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
In addition to helping customers to understand failed connections, this logging will also help debug why a refresh operation failed.
=> chore: add debug logging aroud refresh operation

.github/trusted-contribution.yml
We have way to many Renovate PRs open right now and need to stop the tests from running on every branch change
for every PR. 
This PR will temporarily stop the branches from running. We will revert it once the backlog of renovate PRs is done.
=> ci: disable auto running tests.

jdbc/mysql-j-5/pom.xml
Update the version number on the mysql-5 distributionManagement. It does not get updated automatically by ReleasePlease.
=> chore: fix mysql 5 distribution management.

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
To refresh a Cloud SQL Instance's certificates, the current algorithm uses 2 threads from the thread pool for each
instance. Because the thread pool is fixed size, if a user configures 2 or more instances, they were at risk of a causing
thread starvation and a deadlock. 
This increases the thread count to a safe level so that most users will never experience a deadlock.
Fixes #1314
=> fix: Increase threadpool count to avoid deadlocks

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstanceName.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Update the logic in forceRefresh() to reduce the churn on the thread pool when the certificate refresh API calls are failing. 
New forceRefresh() logic ensures that:
- Only 1 refresh cycle may run at a time. 
- If a refresh cycle is in progress, then it will not be canceled until it succeeds.
Add new test cases to validate race conditions, deadlocks, and concurrency.
Add additional logging to help diagnose production problems with certificate refresh.
Related to #1314
Fixes #1209 
Fixes #1159
=> fix: remove race condition bug in refresh logic

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
For simplicity, we are removing the library dev.failsafe and using a rate limiter already included in 
the Guava library instead.
=> fix: Use guava rate limiter instead of dev.failsafe

.github/workflows/release.yml, .github/workflows/scorecard.yml, .github/workflows/tests.yml, .mvn/wrapper/maven-wrapper.properties, core/pom.xml, jdbc/mariadb/pom.xml, jdbc/mysql-j-5/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, r2dbc/core/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Includes the following dependencies: 
deps: Update ossf/scorecard-action action to v2.2.0
deps: Update dependency maven to v3.9.4
deps: Update dependency com.google.guava:guava to v32.1.2-android
deps: Update dependency com.google.cloud.sql:mysql-socket-factory-connector-j-8 to v1.13.1
deps: Update GoogleCloudPlatform/release-please-action action to v3.7.11
deps: Update graalvm/setup-graalvm digest to c569e64
=> deps: Update multiple dependencies.

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
This removes circular dependencies between the user agent calculation and the SqlAdminApiFetcher. This is necessary 
because to implement of #1168, CoreSocketFactory must change from using a single instance of SqlAdminApiFetcher 
for all Cloud SQL instances to having an instance of SqlAdminApiFetcher per Cloud SQL instance. 
Related to #1168
=> chore: Remove coupling in user agent logic to SqlAdminApiFetcher 

.github/workflows/tests.yml, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/CredentialFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java, core/src/test/java/com/google/cloud/sql/core/RefreshCalculatorTest.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8ServiceAccountImpersonationIntegrationTests.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java, r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java, r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java, r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java
Adds new `delegates` JDBC connection property that will enable users to list the service account delegates
to use when connecting to a database instance. 
part of #1168
=> feat: Add support for service account impersonation.

docs/jdbc-mariadb.md, docs/jdbc-mysql.md, docs/jdbc-postgres.md, docs/r2dbc-mysql.md, docs/r2dbc-postgres.md, docs/r2dbc-sqlserver.md
Add documentation of the new `delegates` property that holds the list of service accounts to impersonate.
fixes #1168
=> docs: Add documentation for Service Account Impersonation feature.

pom.xml
Update to correctly reflect the new configuration used by standard build tools. See [java-shared-config/pom.xml](https://github.com/googleapis/java-shared-config/blob/main/pom.xml#L42) This should unblock the release process.
Additional work needed to update and improve maven configuration is tracked in #1447
=> chore(ci): Fix the distribution management URLs for new build scripts.

core/pom.xml, jdbc/mariadb/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml, jdbc/sqlserver/pom.xml, pom.xml, r2dbc/core/pom.xml, r2dbc/mysql/pom.xml, r2dbc/postgres/pom.xml, r2dbc/sqlserver/pom.xml
Update dependency graalvm to `v23.1.0` and use module `nativeimage`.
Note: The GraalVM SDK `v23.1.0` was split into several more fine-grained modules. The use of the `graalvm-sdk` module is now deprecated ([CHANGELOG](https://github.com/oracle/graal/blob/f72c19ac64e20d94b7166426b303e4e860f58d07/sdk/CHANGELOG.md)).
=> deps: Update dependency graalvm to v23.1.0

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java, core/src/test/java/com/google/cloud/sql/core/StubApiFetcherFactory.java, jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIamAuthIntegrationTests.java, jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java, pom.xml
Fixes #1460
Notes:
* Now the build fails on warnings.
* `Thread.yield();` triggers the warning [ThreadPriorityCheck](https://errorprone.info/bugpattern/ThreadPriorityCheck). So I replaced it by `Thread.sleep(0);` as they may call same system calls in some platforms. Please let me know if you have any other suggestions.
=> chore: fix lint warnings

.github/renovate.json
=> chore: group com.google.auth dependencies in renovate config

pom.xml
Java compilers v20 and higher issue a warning that java 8 source will be deprecated. This change causes 
the compiler not to treat this warning as an error.
=> chore: ignore java 8 deprecation warnings.

core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/PauseCondition.java
Improves the stability of the CloudSqlInstanceTest and CloudSqlInstanceConcurrencyTest. This adds testcases
to cover refresh behavior for tokens near expiration. Also, it adds the PauseCondition so that the testcase can
orchestrate the refresh behavior across threads without resorting to `Thread.sleep()`.
=> test: Testcase improvements for the CloudSqlInstanceTest

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Introduce a new testing parameter to the CoreSocketFactory that sets a maximum time to wait to establish a socket
connection before throwing a TimeoutException. This will make running CoreSocketFactoryTest for failures go 
much faster. 
Also this is a step towards improving the refresh operation.
=> test: set timeout for refresh operation in CoreSocketFactory.

core/pom.xml, pom.xml
Update the maven configuration so that the CLIRR plugin only checks classes that are documented
to be part of our public API.
=> chore: Set project-wide config for CLIRR version compatibility checks

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Rewrite the performRefresh() as a chain of task futures from the ListeningScheduledExecutorService. Now, tasks
submitted to the ListeningScheduledExecutorService never block on another task submitted to the ListeningScheduledExecutorService.
This should fix a category of bugs that show up in exceptions and logs as "connection timed out" or "refresh failed"
or "bad client certificate". These exceptions can occur when the credentials fail to refresh.
This is the underlying bug: The ListeningScheduledExecutorService gets into a state where all its threads are busy
running tasks, all running tasks are blocked waiting for recently submitted task to complete, and the recently
submitted tasks can't start because there are no available threads in the ListeningScheduledExecutorService.
This …
=> fix: Improve handling of futures and threads during refresh.

core/src/main/java/com/google/cloud/sql/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/IpType.java, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/test/java/com/google/cloud/sql/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/config/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java, jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java, jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java, jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerUnitTests.java, pom.xml, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java, r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java, r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java, r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java
Create a value object containing connector configuration properties. This is the stable public Java API that configures
connectors. All connection configuration property names and defaults are constants on the new ConnectionConfig class. 
Logic to interpret a connection Properties object has moved into this class from CoreSocketFactory. This config object is
now passed within the CoreConnectorFactory instead of an long argument list. 
part of #1587 
part of #1226
=> chore: Create a connector configuration value object

core/src/main/java/com/google/cloud/sql/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/ApiFetcherFactory.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcherFactory.java, core/src/test/java/com/google/cloud/sql/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/MockAdminApi.java, core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java, core/src/test/java/com/google/cloud/sql/core/StubApiFetcherFactory.java, docs/jdbc.md, docs/r2dbc.md, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
=> feat: add support for configuring Admin API URL

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/InstanceData.java, core/src/main/java/com/google/cloud/sql/core/Metadata.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java, core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
The new public configuration class IpType should be used throughtout our connector instead of using
strings to represent IpTypes. 
This moves the translation from a String returned by the API into the `SqlAdminApiFetcher`, the class that is responsible for translating API responses into internal data. 
The old unit test `SqlAdminApiFetcherTest.testFetchInstanceData_returnsIpAddresses()` confirms that the translation works correctly.
=> refactor: Use IpType instead of String

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java, core/src/main/java/com/google/cloud/sql/core/InstanceData.java, core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java, core/src/main/java/com/google/cloud/sql/core/Refresher.java, core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java, core/src/test/java/com/google/cloud/sql/core/PauseCondition.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Create a new class Refresher which knows how to refresh a data object with an expiration date. 
This moves the refresh algorithm out of CloudSqlInstance so that it is easier to share the refresh algorithm 
implementation between this project and the AlloyDB Java Connector.  
The api contract of `CloudSqlInstance` used by `CoreSocketFactory` does not change. `CloudSqlInstance` now has a private `Refresher` which it configures to keep `InstanceData` valid. 
```
refresher =
new Refresher<>(
connectionName, // The name of the connector, in refresh log messages
executor, // The executor
// Supplier<ListenableFuture<InstanceData>> which retrieves fresh data.
() ->  instanceDataSupplier.getInstanceData(
this.instanceName, this.accessTokenSupplier, this.authType, executor, keyPair),
new …
```
=> chore: Extract Refresher from CloudSqlInstance

.github/sync-repo-settings.yaml, .github/workflows/tests.yml, pom.xml
Added the quick build mode flag (`-Ob`) to reduce the native build time.
As discussed the GraalVM job will run on periodic (schedule) event as it takes from 7 to 10min to finish.
=> chore: update GraalVM CI build to run only on set schedule

core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java, jdbc/mariadb/src/main/java/com/google/cloud/sql/mariadb/SocketFactory.java, jdbc/mysql-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java, jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java
Introduce the `Connector` class, which can create mTLS connections to a database instance. `ConnectorKey` is used to identify the `Connector` for a `ConnectionConfig`
Part of #1226
=> chore: Add Connector class

core/src/main/java/com/google/cloud/sql/core/ConnectionInfo.java, core/src/main/java/com/google/cloud/sql/core/ConnectionMetadata.java, core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/InstanceMetadata.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/RefresherTest.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
Make a single internal public method to be used by R2DBC drivers to get the metadata needed
to make a connection to a Cloud SQL instance: the TLS config, and the IP address.
=> chore: Introduce ConnectionMetadata for R2DBC factories

core/src/main/java/com/google/cloud/sql/ConnectorRegistry.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/main/java/com/google/cloud/sql/core/Refresher.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java, core/src/test/java/com/google/cloud/sql/core/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java, core/src/test/java/com/google/cloud/sql/core/RefresherTest.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresNamedConnectorIntegrationTests.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
In real usage, an application would first call `Connector.register()` to register the configuration for a named connection.
```java
ConnectorConfig config =  new ConnectorConfig.Builder()
.withTargetPrincipal("example@project.iam.googleapis.com")
.withDelegates(Arrays.asList("delegate@project.iam.googleapis.com"))
.build();
ConnectorRegistry.register("my-connector", config);
```
Then the application would use the connector by adding the `cloudSqlNamedConnector` parameter to the JDBC URL: 
```java
String jdbcUrl = "jdbc:mysql:///<DATABASE_NAME>?"+
+ "cloudSqlInstance=project:region:instance"
+ "&cloudSqlNamedConnector=my-connector"
+ "&socketFactory=com.google.cloud.sql.mysql.SocketFactory"
+ "&user=<DB_USER>&password=<PASSWORD>";
```
Or using JDBC connection properties, by adding the …
=> feat: Java API to configure named connections

core/src/main/java/com/google/cloud/sql/ConnectorConfig.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/ConstantCredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/CredentialFactoryProvider.java, core/src/main/java/com/google/cloud/sql/core/FileCredentialFactory.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/main/java/com/google/cloud/sql/core/SupplierCredentialFactory.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java, core/src/test/java/com/google/cloud/sql/core/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/ConstantCredentialsFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/CredentialFactoryProviderTest.java, core/src/test/java/com/google/cloud/sql/core/FileCredentialFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java, core/src/test/java/com/google/cloud/sql/core/SupplierCredentialFactoryTest.java, core/src/test/resources/sample-credentials.json, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Provides new configuration fields ConnectorConfig that allow the user to connectors use a specific GoogleCredential. users may set one of these three fields: 
- `Supplier<GoogleCredentials> googleCredentialsSupplier` - a supplier to provide GoogleCredentials instances to the connector. 
- `GoogleCredentials googleCredentials` - an instance of GoogleCredentials to use for all requests. 
- `String googleCredentialsPath` - path to file containing GoogleCredentials json. 
Adds a JDBC Connection Property `cloudSqlGoogleCredentialsPath` to set the googleCredentialsPath field.
Fixes #1670
=> feat: Set the GoogleCredentials to use on a connector

jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIamAuthIntegrationTests.java, jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IamAuthIntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8ServiceAccountImpersonationIntegrationTests.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIamAuthIntegrationTests.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIntegrationTests.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresNamedConnectorIntegrationTests.java, jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerIntegrationTests.java, r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java, r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIntegrationTests.java, r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIamAuthIntegrationTests.java, r2dbc/postgres/src/test/java/com/google/cloud/sql/core/R2dbcPostgresIntegrationTests.java, r2dbc/sqlserver/src/test/java/com/google/cloud/sql/core/R2dbcSqlserverIntegrationTests.java
As discussed the test integration timeout should be increased to `80 seconds` to allow for token refresh if needed.
=> chore: increase test timeout to 80 seconds

core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Set the default connect timeout to 45 seconds. This allows the Refresher to retry at least once after 
a failed refresh attempt. (Refresher delay between failed attempts is 30 sec.)
Rename and restructure connect timeout variables to make the code easier to understand.
Fixes #1695.
=> fix: Adjust default timeouts to allow more retries with the Cloud SQL API. 

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
This token stripping seems to have been fixed a long time ago in #565
=> chore: remove unneeded token stripping

.github/renovate.json
Fixes #1735
Test/release/github dependencies commits will have prefix `chore(deps)`.
These commits will be ignored by release-please during the CHANGELOG generation.
=> chore: skip dep commits during changelog generation

.github/renovate.json
No need to update kokoro (release tool) dependencies consistently. Other connectors are not doing it.
=> chore: stop updating kokoro deps

core/pom.xml, core/src/main/java/com/google/cloud/sql/CredentialFactory.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/CredentialFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/CredentialFactoryProviderTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java, core/src/test/java/com/google/cloud/sql/core/StubCredentialFactory.java
* Update the `com.google.auth` dependencies to `v1.21.0`
* Switch from the deprecated  constructor `GoogleCredentials(AccessToken)` to the  constructor `GoogleCredentials(Builder builder)`.
=> deps: Update com.google.auth dependencies to v1.21.0

core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/Refresher.java, core/src/test/java/com/google/cloud/sql/core/RefresherTest.java
When a computer wakes from sleep after more than ~1 hour and a client tries to connect, the internal certificate cache will have an expired certificate. As a result, clients who tried to connect after sleep would see bad certificate errors which would resolve only once the remaining refresh duration expired (sleep time + remaining duration).
This commit adds code to check if the client certificate is expired and immediately triggers a blocking refresh if it is. This means that in the case where a cached certificate has expired, it will be discarded and a new one will be retrieved before continuing with the connection.
Fixes https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/1558
=> fix: ensure cert refresh recovers from sleep

jdbc/mysql-j-8/pom.xml
Note: Maven artifact moved from https://mvnrepository.com/artifact/mysql/mysql-connector-java to https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
Fixes #1831
=> deps: Update dependency com.mysql:mysql-connector-j to v8.3.0

jdbc/mariadb/pom.xml, jdbc/mysql-j-8/pom.xml, jdbc/postgres/pom.xml
Doing the solution suggested in  #1858, but for all the jdbc drivers, as they all seem to have the same problem.
It compiles correctly, test also compile but I'm unable to run them locally.
Fixes #1858
=> fix: Guava dependency missing from jar-with-dependencies

core/src/main/java/com/google/cloud/sql/core/FileCredentialFactory.java
The OAuth scopes for [Cloud SQL Admin API](https://developers.google.com/identity/protocols/oauth2/scopes#sqladmin) should be set for the credentials defined by a JSON file as we do for the [Default Credentials](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/main/java/com/google/cloud/sql/core/ApplicationDefaultCredentialFactory.java#L49).
Fixes #1904
=> fix: Add scope for Credentials defined by a JSON file

pom.xml
Updated the following dependencies:
* `com.google.guava:guava` to `v33.1.0-android`
* `com.google.api-client:google-api-client` to `v2.4.0`
Added `com.google.j2objc:j2objc-annotations` to `<dependencyManagement>` to use the newest version to fix this error:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (enforce) on project jdbc-socket-factory-core: 
Error:  Rule 0: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
Error:  Failed while enforcing releasability.
Error:  
Error:  Dependency convergence error for com.google.j2objc:j2objc-annotations:jar:2.8 paths to dependency are:
Error:  +-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.17.1-SNAPSHOT
Error: …
```
=> chore(deps): Update deps guava and google-api-client to the latest version

core/pom.xml
Update GAX dependency scope to `provided` as it is only required for GraalVM support.
Related to #1921
=> chore: Update GAX dependency scope to provided.

.github/scripts/run_tests.sh, .github/sync-repo-settings.yaml, .github/workflows/tests.yml, pom.xml
Integration runs on latest Java version on Linux. Units run on Java 8, 11, 17 versions on Linux, Windows, and macOS. We don't have integration test support for multiple OSes, so we lean on unit tests there.
Fixes #1877
=> chore: pare down test size

core/src/main/java/com/google/cloud/sql/ConnectorRegistry.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
The following issue was reported in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2773:
the warning `Application name is not set. Call Builder#setApplicationName.` is logged by `com.google.api.client.googleapis.services.AbstractGoogleClient` when `using com.google.cloud:spring-cloud-gcp-starter-sql-postgresql`
The issue was caused by setting the Artifact ID using the instance method instead of the static one. Additionally, the library version was added to the Artifact ID by default, resulting in user agents like `spring-cloud-gcp-sql/5.1.2/1.17.2-SNAPSHOT mysql-socket-factory-connector-j-8/1.17.2-SNAPSHOT`. This issue has been fixed.
=> fix: Set Artifact ID using the static method.

docs/jdbc.md
JDBC README shows incorrect dependency for SQL Server usage.
I believe it should be `cloud-sql-connector-jdbc-sqlserver`?
=> chore: fix JDBC readme SQL Server dependency

core/src/main/java/com/google/cloud/sql/ConnectorConfig.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryFactory.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java, core/src/test/resources/sample-credentials.json, docs/configuration.md, docs/jdbc.md, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
Add support for Trusted Partner Cloud (TPC) environments through `cloudSqlUniverseDomain` property.
Example: 
```
Properties connProps = new Properties();
connProps.setProperty("cloudSqlUniverseDomain", "test-universe.test");
```
Fixes #1894
=> feat: add support for TPC

core/pom.xml, core/src/main/java/com/google/cloud/sql/nativeimage/CloudSqlFeature.java, core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/jni-unix-socket-config.json, core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/native-image.properties, core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/proxy-config.json, core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/resource-config.json, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/FakeUnixSocketServer.java, pom.xml
This is a fix for the graalvm configuration issues related to the jnr.unixsocket library. 
- The proxy classes are now being properly configured for reflection and dynamic proxy.
- Native library files that are usually loaded as resources from jffi-1.3.13-native.jar are included in the build. 
Fixes #1940
=> fix: Configure unix socket library for Graalvm

core/src/main/java/com/google/cloud/sql/ConnectorConfig.java, core/src/main/java/com/google/cloud/sql/RefreshStrategy.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectionConfigTest.java, r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
This adds the new JDBC and R2DBC configuration property `refreshStrategy` with valid values `lazy` or `background`. 
For R2DBC, the configuration option is named 'REFRESH_STRATEGY' to match formatting of the 
other configuration options. 
Part of #992.
=> chore: Add refreshStrategy connector configuration (part of #992)

core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/StubConnectionInfoRepository.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Adds a new method ConnectionInfoRepository.getConnectorInfoSync() which blocks until it can return a valid 
ConnectorInfo. Adds the implementation of this new method to DefaultConnectionInfoRepository.  This is used 
by the LazyRefresher to fetch connection info on the active thread.  
Part of Lazy Refresh #992.
=> chore: Add synchronous operation to DefaultConnectionInfoRepository (part of #992)

core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/native-image.properties
Removes the -H:+BuildReport flag from the native image module configuration. This will allow builds
on GraalVM CE to run successfully.
Fixes #1979
=> fix: Remove native image flag that breaks GraalVM CE builds.

core/pom.xml, core/src/main/java/com/google/cloud/sql/core/ConscryptWorkaroundDelegatingTrustManger.java, core/src/main/java/com/google/cloud/sql/core/ConscryptWorkaroundTrustManagerFactory.java, core/src/main/java/com/google/cloud/sql/core/ConscryptWorkaroundTrustManagerFactorySpi.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, jdbc/postgres/pom.xml, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresIamAuthIntegrationTests.java, jdbc/postgres/src/test/resources/conscrypt-security.properties, pom.xml
This is a workaround for an underlying bug in the Google Conscrypt crypto library 
[google/conscrypt #1033](https://github.com/google/conscrypt/issues/1033). 
The root cause is that the Conscrypt and OpenJDK X509 certificate libraries sometimes interpret the AuthType 
field differently: Conscrypt finds 'GENERIC' auth type when OpenJDK finds 'UNKNOWN' auth type. This causes certificate validation to fail. 
The workaround implemented here is to add a delegate `TrustManager` that replaces 'GENERIC' auth type with 'UNKNOWN' auth type so that the Conscrypt crypto plays nice with the JDK crypto. [See comment on #1033](https://github.com/google/conscrypt/issues/1033#issuecomment-982701272). 
I manually tested this on a modified JVM that used Conscrypt as it's primary crypto library. The …
=> fix: Add TrustManagerFactory workaround for Conscrypt bug

jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresLazyRefreshIntegrationTests.java
Creating a new lazy refresh strategy will make connectors more reliable on Cloud Run and other serverless platforms. 
Fixes #992
=> test: Adds integration test of the Lazy Refresh strategy. Part of #992.

.github/renovate.json5
This should simplify the renovate dependency configuration for the Java library, resulting in fewer deps PRs.
=> chore: Fix renovate config to consolidate dependencies.

.github/workflows/tests.yml, pom.xml
Future update needed to use a managed version for `graal-sdk.version`, but we need to release java-shared-config with https://github.com/googleapis/java-shared-config/pull/852 before it will be available.
Future update needed to use a managed GraalVM test image.
=> ci: test with graalvm-community and use managed native image maven plugin

core/src/main/java/com/google/cloud/sql/core/ApiClientRetryingCallable.java, core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java, core/src/test/java/com/google/cloud/sql/core/ApiClientRetryingCallableTest.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java
This updates the retry logic for API calls made by the connector: 
- Attempts to get an authentication token from the Google auth API are always retried 5 times.
- SQL Admin API requests are retried up to 5 times if the http response status code is a 5xx. Otherwise they are fatal on the first error.
This also implements the exponential backoff logic defined used in the go connector.
See: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/781
=> feat: Retry API calls that return a 500 error

core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/DnsInstanceConnectionNameResolver.java, core/src/main/java/com/google/cloud/sql/core/InstanceConnectionNameResolver.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/DnsSrvRecordTest.java
A connection may be configured to using a DNS name instead of an instance name. If the cloudSqlInstance property is
set to be a domain name instead of an instance name, the connector will look up a SRV record for that name and
connect to that instance.
There should be exactly 1 SRV for the database instance. The connector will always use the SRV record with the
highest priority.
Part of #2043
=> feat: Automatically configure connections using DNS. Part of #2043.

core/src/test/resources/logback.xml
If developers wish to re-enable debug logs, change the root level to "debug."
=> chore: turn off test log noise by default

.github/workflows/tests.yml
Pull request from forks once merged will still be skipped because `github.event.pull_request.head.repo.full_name` will still be that of the fork.
To combat this we run the job on all events that are not a pull_request (aka `schedule` and `push`)
=> ci: skip integration tests on fork PRs

core/src/test/java/com/google/cloud/sql/core/ServiceAccountImpersonatingCredentialFactoryIntegrationTests.java
This actually instantiates real Google Cloud credentials using the API, and therefore needs
to be treated as an integration test instead of a unit test.
=> test: Move ServiceAccountImpersonatingCredentialFactoryTest to integration tests.

.github/workflows/tests.yml
Update unit tests to not have access to secret manager secrets.
=> ci: remove secret manager secrets from unit tests

core/src/main/java/com/google/cloud/sql/core/DnsResolver.java, core/src/main/java/com/google/cloud/sql/core/JndiDnsResolver.java
This is a prerequisite for other implementation steps in the Automatic Failover with DNS Configuration story.
Part of #2043.
=> chore: Create a new DnsResolver class that wraps the Java DNS API

core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/LazyRefreshConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/LazyRefreshStrategy.java, core/src/main/java/com/google/cloud/sql/core/RefreshCalculator.java, core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java
Added a 4 minute buffer to refreshing tokens and certificates to avoid creating race condition that would allow the connector to create an ephemeral certificate with an expired auth token. 
Now, IAM auth tokens are now refreshed 4 minutes before they token expire. Also, the Lazy Refresh Strategy will refresh the client certificate 4 minutes before the expiration of the certificate and the IAM auth token. 
This should mitigate some of the strange certificate expiration errors commonly found in Cloud Run, see: #2059
=> fix: Lazy refresh should refresh tokens 4 minutes before expiration.

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactory.java, core/src/main/java/com/google/cloud/sql/core/InstanceMetadata.java, core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java, core/src/test/java/com/google/cloud/sql/core/MockAdminApi.java, core/src/test/java/com/google/cloud/sql/core/RefreshAheadConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/RefreshAheadStrategyTest.java, core/src/test/java/com/google/cloud/sql/core/StubConnectionInfoRepository.java, core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Refactor InstanceMetadata to include fields needed to validate the TLS server certificates from CAS-
enabled instances. This contains only changes to the data structure of InstanceMetadata. It does not change
to the certificate validation logic.
=> chore(refactor): Add CAS related fields to the InstanceMetadata.

core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactory.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactorySpi.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManger.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/FakeSslServer.java, core/src/test/java/com/google/cloud/sql/core/MockAdminApi.java, core/src/test/java/com/google/cloud/sql/core/TestCertificateGenerator.java, core/src/test/java/com/google/cloud/sql/core/TestKeys.java
For Cloud SQL instances with CAS enabled, the connector will use the certificate chain of trust reported by the 
SQL Admin API to validate the instance connection.
=> feat: Support CAS server certificate authority to validate instance connections.

core/src/main/java/com/google/cloud/sql/ConnectorConfig.java, core/src/main/java/com/google/cloud/sql/CredentialFactory.java, core/src/main/java/com/google/cloud/sql/RefreshStrategy.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/RefreshStrategy.java
The checkstyle rules are becoming more strict. All public methods must now have javadoc.
=> docs: Add missing javadoc comments to public methods.

.github/workflows/tests.yml
The main branch GraalVM integration tests failed because they were missing the secrets to the Postgres CAS instance.
This fixes the build configuration so that the secrets are set.
=> test: Add Postgres CAS secrets to the graalvm integration tests.

core/src/main/java/com/google/cloud/sql/ConnectorConfig.java, core/src/main/java/com/google/cloud/sql/core/CloudSqlInstanceName.java, core/src/main/java/com/google/cloud/sql/core/ConnectionConfig.java, core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/LazyRefreshConnectionInfoCache.java, core/src/main/java/com/google/cloud/sql/core/RefreshAheadConnectionInfoCache.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java
Add DomainName to connection config, and an InstanceNameResolver function. This will allow the connector
to be configured using a domain name referencing the instead of the instance name.
This is part of the implementation of #2043. 
See #2043 for the whole feature definition.
=> chore: Add domain name to the connector config.

jdbc/mariadb/src/main/java/com/google/cloud/sql/mariadb/SocketFactory.java, jdbc/mysql-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8DomainNameIntegrationTests.java, jdbc/mysql-j-8/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ8IntegrationTests.java, jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java, jdbc/postgres/src/test/java/com/google/cloud/sql/postgres/JdbcPostgresDomainNameIntegrationTests.java
When connecting to a Cloud SQL database using a domain name like `db.example.com`, 
you may now set the domain name in the JDBC URL. For example, you can use a URL like
"jdbc:mysql://db.example.com/my-schema?socketFactory=com.google.cloud.sql.mysql.SocketFactory"
The socket factory will detect "db.example.com" and look up the TXT record to resolve
the instance name. 
Adding this capability to the SQLServer driver will be a separate PR.
See https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/2043 for the whole feature definition.
=> chore: Use domain name from JDBC URL for Postgres and Mysql, Part of #2043

docs/jdbc.md, docs/r2dbc.md
Adds documentation to describe how to use the hostname for JDBC and R2DBC.
=> docs: Add docs for connector configuration using DNS Names, Part of #2043

core/src/main/java/com/google/cloud/sql/core/CloudSqlInstanceName.java, docs/jdbc.md, docs/r2dbc.md, jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java, jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerIntegrationTests.java, jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerUnitTests.java
Enables Sql Server users to set the domain name in the JDBC URL. Users simply replace the instance connection
name with the domain name.
Due to limitations of the SQL Server driver, users cannot use the JDBC URL's host field.
=> chore: Use domain name from JDBC URL for SQL Server, Part of #2043.

r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
When the java connector was refactored to use ConnectorConfig and ConnectionConfig value objects, it was no longer necessary to pre-fetch the connection configuration to ensure that enableIamAuth was set correctly. Also, this is inconsistent behavior compared to the JDBC socket factory.
=> refactor: Remove unnecessary pre-fetching from R2DBC.

r2dbc/core/pom.xml, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
This adds a new test to check that the GcpConnectionFactoryProvider correctly configures the ConnectionConfiguration.
This also removes up unused test setup code from the GcpConnectionFactoryProviderTest.
=> test: Add tests for R2DBC connector configuration

r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java, r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Now, the connector will detect if the R2DBC `HOST` connection property contains a domain name or a 
Cloud SQL instance name. If `HOST` has a domain name, the connector will look up the domain name to
determine the instance name. 
For example, if the R2DBC url is set to `r2dbc:gcp:mssql://<DB_USER>:<DB_PASS>@db.example.com/db`,
the connector will lookup the TXT record for `db.example.com`. The record should contain a valid
Cloud SQL instance name. 
Part of #2043
=> chore: Use domain name from R2DBC connections, Part of #2043.

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManger.java, core/src/test/java/com/google/cloud/sql/core/CloudSqlCoreTestingBase.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryTest.java, core/src/test/java/com/google/cloud/sql/core/MockAdminApi.java, core/src/test/java/com/google/cloud/sql/core/TestCertificateGenerator.java, pom.xml
When the connector is configured with a DNS name, or if the Cloud SQL Instance reports that it has a DNS Name,
the connector will use standard TLS hostname validation when checking the server certificate. Now, the server's
TLS certificate must contain a SAN record with the instance's DNS name.
The ConnectSettings API added a field dns_names which contains all of the valid DNS names for
an instance..
See also https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/954
=> feat: Use standard TLS hostname validation for instances with DNS names.

core/src/main/java/com/google/cloud/sql/core/Connector.java, core/src/main/java/com/google/cloud/sql/core/MonitoredCache.java, core/src/test/java/com/google/cloud/sql/core/MonitoredCacheTest.java
The list `sockets` on the `MonitoredCache` should only keep track of
sockets opened for connections using a domain name.
It should not keep track of all sockets for regular connections.
This is what it is currently doing:
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/a5329ac62ce877783c447f4192b62e72f39b63d4/core/src/main/java/com/google/cloud/sql/core/Connector.java#L141
Sockets are only removed from the list if the connections were made using a domain name:
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/a5329ac62ce877783c447f4192b62e72f39b63d4/core/src/main/java/com/google/cloud/sql/core/MonitoredCache.java#L92-L96
Thus for sockets not using a domain name and using the default instance connection name pattern, the sockets list will …
=> fix: only keep track of sockets opened using domain name

core/src/main/resources/META-INF/native-image/com.google.cloud.sql/cloud-sql-jdbc-socket-factory-parent/native-image.properties
The GraalVM flag UnlockExperimentalVMOptions is not supported in GrallVM 17.0, 
and is not required in 21.0 or 23.0. Removing the flag restores compatibility 
with GraalVM 17.
Fixes #2140
=> fix: Remove unsupported GraalVM UnsupportedExperimentalVMOptions flag.

pom.xml
Roll back from Netty 4.2.0.Final to 4.1.119.Final. 
The upgrade to Netty 4.2.0.Final broke R2DBC tests. We will need to investigate further before we upgrade Netty.
```
Error:  com.google.cloud.sql.core.R2dbcMariadbIntegrationTests.pooledConnectionTest -- Time elapsed: 0.280 s <<< ERROR!
io.r2dbc.spi.R2dbcNonTransientResourceException: [9000] [H1000] Fail to establish connection to [34.72.43.231:3307] : Connection error
at org.mariadb.r2dbc.ExceptionFactory.createParsingException(ExceptionFactory.java:66)
at org.mariadb.r2dbc.HaMode.resumeConnect(HaMode.java:157)
at org.mariadb.r2dbc.HaMode.lambda$connectHost$7(HaMode.java:206)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMa …
```
=> fix: Roll back dependency update that broke R2DBC + MariaDB IAM E2E Test

core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactory.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManger.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/InstanceCheckingTrustManagerFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/TestCertificateGenerator.java
This updates the logic used by the connector to validate server certificates.
When connecting to the instance, the connector's TLS validator will first check the SAN field,
and then if that fails check the CN field in the certificate for the instance name. This will enable
the connector to work smoothly with both legacy and newer instances.
To summarize the deviations from standard TLS hostname verification:
Historically, Cloud SQL creates server certificates with the instance name in the Subject.CN field in 
the format "my-project:my-instance". The connector is expected to check that the instance name
that the connector was configured to dial matches the server certificate Subject.CN field. Thus, 
the Subject.CN field for most Cloud SQL instances does not contain a well-formed DNS Name. …
=> feat: Update TLS validation to use both SAN and CN fields.

.ci/cloudbuild.yaml, .github/scripts/run_tests.sh
This better matches Github Action build configuration to Cloud build.
=> ci: Update to use zulu-openjdk-17 image for integration tests.

core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java, core/src/main/java/com/google/cloud/sql/core/InstanceCheckingTrustManger.java, core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java, core/src/main/java/com/google/cloud/sql/core/JndiDnsResolver.java, core/src/test/java/com/google/cloud/sql/ConnectorConfigTest.java, core/src/test/java/com/google/cloud/sql/CredentialFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/ApiClientRetryingCallableTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectionConfigTest.java, core/src/test/java/com/google/cloud/sql/core/ConnectorTest.java, core/src/test/java/com/google/cloud/sql/core/ConstantCredentialsFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java, core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryTest.java, core/src/test/java/com/google/cloud/sql/core/FileCredentialFactoryTest.java, core/src/test/java/com/google/cloud/sql/core/LazyRefreshConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java, core/src/test/java/com/google/cloud/sql/core/MonitoredCacheTest.java, core/src/test/java/com/google/cloud/sql/core/RefreshAheadConnectionInfoCacheConcurrencyTest.java, core/src/test/java/com/google/cloud/sql/core/RefreshAheadConnectionInfoCacheTest.java, core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java, core/src/test/java/com/google/cloud/sql/core/ServiceAccountImpersonatingCredentialFactoryIntegrationTests.java, core/src/test/java/com/google/cloud/sql/core/SupplierCredentialFactoryTest.java
This contains superficial changes to annotations. This tags specific fields labeled as deprecated in the javadoc
with `@Deprecated` annotation. Also, this adds `@RunWith(JUnit4.class)` to several test cases to make 
the test classes explicit.
=> chore: Superficial annotations for Deprecated and test runner.

.gitignore, core/pom.xml, core/src/main/java/com/google/cloud/sql/core/DnsJavaResolver.java, core/src/test/java/com/google/cloud/sql/core/DnsJavaResolverTest.java, pom.xml
Description:
This PR Adds the following:
1. The dnsjava dependency, and a new class `DnsJavaResolver`. Which will be use to replace `JndiDnsResolver` for DNS record lookup. 
2. DnsJavaResolverTest to make sure DnsJavaResolver are working as expected
Next:
Will replace and remove `JndiDnsResolver` with `DnsJavaResolver` in the next PR.
=> feat: Add DnsJavaResolver and related test
